// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Ping(ctx context.Context, in *rpc.Request) (*rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcServer) TestA(ctx context.Context, in *rpc.TestReq) (*rpc.TestResp, error) {
	l := logic.NewTestALogic(ctx, s.svcCtx)
	return l.TestA(in)
}

func (s *RpcServer) TestB(ctx context.Context, in *rpc.TestReq) (*rpc.TestResp, error) {
	l := logic.NewTestBLogic(ctx, s.svcCtx)
	return l.TestB(in)
}
