// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package rpcclient

import (
	"context"

	"rpc/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpc.Request
	Response = rpc.Response
	TestReq  = rpc.TestReq
	TestResp = rpc.TestResp

	Rpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		TestA(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error)
		TestB(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultRpc) TestA(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.TestA(ctx, in, opts...)
}

func (m *defaultRpc) TestB(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.TestB(ctx, in, opts...)
}
